# Generated by Django 4.2.11 on 2024-03-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(related_name='books', through='books.BookSubjects', to='books.subject'),
        ),
        migrations.AlterField(
            model_name='booksubjects',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booksubjects', to='books.book'),
        ),
    ]
