# Generated by Django 4.2.11 on 2024-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_subjects_alter_booksubjects_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_languages',
            field=models.ManyToManyField(related_name='books', to='books.language'),
        ),
    ]
